apiVersion: kdev.deranged.dk/v1
kind: Cluster
metadata:
  name: os2ai-local-deranged-dk
spec:
  kind:
    version: "1.34"
  config:
    domain: os2ai.local.deranged.dk
    registry: registry.local.deranged.dk
